# Generated by Django 5.2.7 on 2025-10-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.AddField(
            model_name='resource',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL to the external file.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Use HTML or Markdown for content, including <img> tags for inline images using their URLs.'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('is_banner', models.BooleanField(default=False, help_text='Check if this is the banner image; others can be referenced in the article content via their URLs.')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.article')),
            ],
            options={
                'ordering': ['-is_banner'],
            },
        ),
    ]
